const $=id=>document.getElementById(id);const today=new Date();
const opts={identity:['高中生','国际高中','普高','本科在读','大一','大二','大三','大四','已毕业','在职','硕士在读','博士意向','家长咨询'],stage:['本科','硕士','博士','转学','预科','语言学校','暑校','背景提升','竞赛','实习','科研','作品集'],system:['普高','IB','A-Level','AP','IGCSE','OSSD','DSE','VCE','美高','加高','海本','中外合作','国内本科','其他'],grade:['G9','G10','G11','G12','大一','大二','大三','大四','往届','在职','其他'],country:['英国','中国香港','新加坡','澳大利亚','新西兰','加拿大','美国','中国澳门','马来西亚','欧陆','日本','韩国','多地联申','未定'],major:['商科金融','会计','管理','经济','数据','计算机','工程','生物医学','化学','物理','数学','教育','法律','传媒','心理','艺术','人文社科','医学相关','不确定'],ranking:['G5','牛剑','QS前50','QS前100','港前三','港五','八大','藤校','Top30','Top50','Top100','不确定'],languageTest:['雅思','托福','多邻国','日语','韩语','未考'],exam:['SAT','ACT','GRE','GMAT','LNAT','TMUA','ESAT','UCAT','ISAT','无'],subscore:['是','否','不确定'],budget:['1万以内','1-3万','3-6万','6-10万','10-20万','20万以上','待沟通'],scenario:['初次咨询','已发资料未回复','家长犹豫价格','家长想比较机构','目标不清晰','已有其他机构方案','需要促成面谈','需要签约收口','学生时间紧','家长说暑假再说','想先了解不着急']};
const backgrounds=['无明显背景','有实习','有科研','有竞赛','有论文','有夏校','有作品集','有志愿者','有社团活动','有推荐信资源','有导师资源','有工作经历'];
const weaknesses=['语言未达标','GPA/校内成绩弱','目标国家不明确','专业方向不明确','申请时间紧','背景活动空白','实习经历不足','科研经历不足','文书主线弱','面试能力弱','家长预算敏感','需要考研/保研兜底','需要就业导向规划','需要高端名校冲刺','需要签证/住宿/行前服务','需要作品集','需要竞赛奖项','需要学术成绩提升'];
const concerns=['录取稳定性','名校排名','专业就业','价格性价比','服务透明','文书质量','导师背景','背景提升产出','时间效率','双保险退费/保障机制','后续签证住宿服务','是否能提供定校建议'];
const resources={英国:[['UCAS Course Search','https://www.ucas.com/explore/search/courses'],['Discover Uni','https://discoveruni.gov.uk/'],['Prospects','https://www.prospects.ac.uk/'],['FindAMasters','https://www.findamasters.com/'],['FindAPhD','https://www.findaphd.com/']],中国香港:[['Study in Hong Kong','https://www.studyinhongkong.edu.hk/en/hong-kong-education/programme-list.php'],['HKU','https://www.hku.hk/'],['CUHK','https://www.cuhk.edu.hk/'],['HKUST','https://hkust.edu.hk/'],['PolyU','https://www.polyu.edu.hk/']],新加坡:[['NUS','https://www.nus.edu.sg/'],['NTU','https://www.ntu.edu.sg/'],['SMU','https://www.smu.edu.sg/']],澳大利亚:[['Study Australia','https://www.studyaustralia.gov.au/en/plan-your-studies/find-a-course'],['CRICOS','https://cricos.education.gov.au/']],加拿大:[['EduCanada','https://www.educanada.ca/programs-programmes/index.aspx?lang=eng'],['DLI List','https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/prepare/designated-learning-institutions-list.html']],美国:[['Common App','https://www.commonapp.org/'],['BigFuture','https://bigfuture.collegeboard.org/'],['GradSchools','https://www.gradschools.com/']],欧陆:[['DAAD','https://www.daad.de/en/studying-in-germany/universities/all-degree-programmes/'],['Campus France','https://www.campusfrance.org/en'],['Study in NL','https://www.studyinnl.org/'],['Study in Sweden','https://studyinsweden.se/']],日本:[['JASSO Study in Japan','https://www.studyinjapan.go.jp/en/']],韩国:[['Study in Korea','https://www.studyinkorea.go.kr/']]};
const products=[
{name:'中国香港维港计划',code:'ZHB-133262',cat:'留学申请',country:'中国香港',stage:'本科/硕士',price:'20000/优惠18000',tags:['香港','港校','单地区'],desc:'8个项目/2个细分专业，含规划、申请、签证签注。'},
{name:'紫藤留学午阳计划A',code:'ZHB-128906',cat:'留学申请',country:'多地区',stage:'本科/硕士',price:'10000/优惠8000',tags:['预算友好','单地区'],desc:'3个项目/1个细分专业，适合目标明确、基础申请。'},
{name:'紫藤留学英才多地计划A',code:'ZHB-128847',cat:'留学申请',country:'多地联申',stage:'本科/硕士',price:'28000/优惠26000',tags:['英港新澳','多地联申','主推'],desc:'10个项目/2个细分专业，最多3地区。'},
{name:'紫藤留学英才多地计划B',code:'ZHB-128848',cat:'留学申请',country:'多地联申',stage:'本科/硕士',price:'32000/优惠30000',tags:['英港新澳','多地联申','主推'],desc:'12个项目/2个细分专业，最多4地区。'},
{name:'英联邦学术科直通计划',code:'ZHB-137351',cat:'本科申请',country:'英联邦',stage:'本科',price:'20000/优惠17000',tags:['本科','UCAS'],desc:'5个课程志愿，不超过2个专业大类。'},
{name:'英国本科Mentor领录计划',code:'ZHB-137394',cat:'高端本科',country:'英国',stage:'本科',price:'48000/优惠45000',tags:['G5','牛剑','笔面试'],desc:'含背景规划、Mentor探索、G5笔面试、外籍文书等。'},
{name:'美国研究生高领计划',code:'ZHB-106251',cat:'硕士申请',country:'美国',stage:'硕士',price:'69800',tags:['美国硕士','系统服务'],desc:'10个项目/2个细分专业，含规划、选校、文书、签证。'},
{name:'美国研究生高才计划',code:'ZHB-124331',cat:'硕士申请',country:'美国',stage:'硕士',price:'55000',tags:['美国硕士','性价比'],desc:'8个项目/1个细分专业。'},
{name:'博航计划（研究型硕士）',code:'ZHB-136594',cat:'研究型申请',country:'英澳新等',stage:'硕士/博士',price:'59800',tags:['RP','套磁','研究型'],desc:'含RP指导、套磁、导师筛选。'},
{name:'欧陆公立卓越计划',code:'ZHB-114477',cat:'欧陆申请',country:'欧陆',stage:'本科/硕士',price:'18000/可优惠15000',tags:['欧陆','公立'],desc:'5个志愿/1语种/1专业方向。'},
{name:'日本SGU青空优才计划',code:'ZHB-049855',cat:'日本申请',country:'日本',stage:'本科/硕士',price:'42000',tags:['英语授课','SGU'],desc:'3个项目，适合英语授课、成绩优秀。'},
{name:'创新产业科研项目A',code:'SP-132957',cat:'科研背提',country:'远程',stage:'背景提升',price:'19800',tags:['科研','双一流'],desc:'适合高中生/大学生，项目证明、科研经历。'},
{name:'英美名校教授小班课远程科研',code:'ZHB-082753',cat:'科研背提',country:'英美',stage:'背景提升',price:'32800',tags:['海外教授','科研'],desc:'教授班课+科研写作指导，约6个月+6周。'},
{name:'四大事务所实习',code:'SP-138536',cat:'实习背提',country:'远程/实地',stage:'背景提升',price:'25800起',tags:['商科','实习','四大'],desc:'适合商科/会计/金融/审计方向。'},
{name:'八大事务所实习',code:'SP-138537',cat:'实习背提',country:'远程/实地',stage:'背景提升',price:'16800起',tags:['商科','实习','八大'],desc:'八大定向，商科相关背景补充。'},
{name:'名企导师职业规划',code:'MENTOR-CAREER',cat:'导师服务',country:'不限',stage:'背景提升',price:'2000',tags:['职业规划','文书主线'],desc:'1V1职业规划1小时，输出职业规划报告。'},
{name:'GPA+绩点提升计划20课时',code:'ZHB-123653',cat:'学术辅导',country:'不限',stage:'学术提升',price:'12000/优惠1000',tags:['GPA','成绩提升'],desc:'适合GPA/校内成绩弱，学籍期12个月。'},
{name:'一对一RP辅导',code:'ZHB-105326',cat:'研究辅导',country:'不限',stage:'硕士/博士',price:'31800/16小时',tags:['RP','研究计划'],desc:'适合博士、研究型硕士RP写作较弱。'},
{name:'艺术轻藤计划Lite',code:'ZHB-121870',cat:'艺术申请',country:'英联邦',stage:'本科/硕士',price:'38000',tags:['作品集','艺术'],desc:'含作品集辅导、6个院校、2个专业。'}];
const schoolPools={英国:{high:[['伦敦大学学院','University College London (UCL)'],['伦敦国王学院','King’s College London'],['爱丁堡大学','University of Edinburgh'],['曼彻斯特大学','University of Manchester']],match:[['布里斯托大学','University of Bristol'],['格拉斯哥大学','University of Glasgow'],['伯明翰大学','University of Birmingham'],['南安普顿大学','University of Southampton']],safe:[['伦敦玛丽女王大学','Queen Mary University of London'],['利兹大学','University of Leeds'],['谢菲尔德大学','University of Sheffield'],['诺丁汉大学','University of Nottingham']]},中国香港:{high:[['香港大学','The University of Hong Kong (HKU)'],['香港中文大学','The Chinese University of Hong Kong (CUHK)'],['香港科技大学','The Hong Kong University of Science and Technology (HKUST)']],match:[['香港理工大学','The Hong Kong Polytechnic University (PolyU)'],['香港城市大学','City University of Hong Kong (CityUHK)'],['香港浸会大学','Hong Kong Baptist University (HKBU)']],safe:[['岭南大学','Lingnan University'],['香港教育大学','The Education University of Hong Kong (EdUHK)'],['香港都会大学','Hong Kong Metropolitan University (HKMU)']]},澳大利亚:{high:[['墨尔本大学','The University of Melbourne'],['悉尼大学','The University of Sydney'],['新南威尔士大学','UNSW Sydney']],match:[['莫纳什大学','Monash University'],['昆士兰大学','The University of Queensland'],['阿德莱德大学','The University of Adelaide']],safe:[['悉尼科技大学','University of Technology Sydney'],['麦考瑞大学','Macquarie University'],['迪肯大学','Deakin University']]},美国:{high:[['纽约大学','New York University'],['南加州大学','University of Southern California'],['密歇根大学安娜堡分校','University of Michigan, Ann Arbor']],match:[['东北大学','Northeastern University'],['波士顿大学','Boston University'],['伊利诺伊大学香槟分校','University of Illinois Urbana-Champaign']],safe:[['亚利桑那州立大学','Arizona State University'],['迈阿密大学','University of Miami'],['乔治梅森大学','George Mason University']]},加拿大:{high:[['多伦多大学','University of Toronto'],['英属哥伦比亚大学','University of British Columbia'],['麦吉尔大学','McGill University']],match:[['滑铁卢大学','University of Waterloo'],['阿尔伯塔大学','University of Alberta'],['麦克马斯特大学','McMaster University']],safe:[['渥太华大学','University of Ottawa'],['西蒙菲莎大学','Simon Fraser University'],['约克大学','York University']]}};
const competitions=[['商科金融','NEC/IEO/FBLA/BPA/SIC','适合经济、金融、管理、商业分析方向'],['计算机','USACO','适合计算机、数据、AI方向'],['生物医学','BBO/USABO/BrainBee/HOSA','适合生物、医学、心理、脑科学方向'],['艺术','作品集辅导/艺术轻藤','适合艺术、设计、建筑、视觉传媒方向']];
function fillSelect(id,arr){$(id).innerHTML=arr.map(x=>`<option>${x}</option>`).join('')}function checks(id,arr){$(id).innerHTML=arr.map(x=>`<label><input type="checkbox" value="${x}">${x}</label>`).join('')}function val(id){return $(id).value}function checked(id){return [...$(id).querySelectorAll('input:checked')].map(i=>i.value)}function toast(t='已复制'){let el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function init(){Object.entries(opts).forEach(([k,v])=>fillSelect(k,v));fillSelect('toolCountry',opts.country);fillSelect('toolStage',opts.stage);fillSelect('intake',buildIntakes());checks('backgroundBox',backgrounds);checks('weaknessBox',weaknesses);checks('concernBox',concerns);$('todayBadge').textContent='当前咨询时间：'+today.toLocaleDateString('zh-CN');fillFilters();renderLibrary();$('customRules').value=localStorage.getItem('customRules')||''}
function buildIntakes(){let y=today.getFullYear();return [`${y}春季`,`${y}秋季`,`${y+1}春季`,`${y+1}秋季`,`${y+2}春季`,`${y+2}秋季`,`${y+3}春季`,'未定']}
function data(){return {name:val('studentName')||'该学生',identity:val('identity'),stage:val('stage'),system:val('system'),grade:val('grade'),intake:val('intake'),country:val('country'),major:val('major'),ranking:val('ranking'),targetSchools:val('targetSchools'),score:val('score')||'未补充',languageTest:val('languageTest'),languageScore:val('languageScore')||'未补充',exam:val('exam'),subscore:val('subscore'),budget:val('budget'),scenario:val('scenario'),backgrounds:checked('backgroundBox'),weaknesses:checked('weaknessBox'),concerns:checked('concernBox')}}
function timeRisk(d){if(d.intake==='未定')return ['未定','建议先明确目标入学季，再倒推语言、背景和申请节点。',18];let y=parseInt(d.intake),m=d.intake.includes('春')?1:9;let months=(y-today.getFullYear())*12+(m-today.getMonth()-1);if(months<6)return ['时间非常紧','优先确认地区、院校要求、材料和语言，背景提升建议短周期项目。',months];if(months<12)return ['时间较紧','申请服务、语言和背景补强需要同步推进。',months];if(months<24)return ['规划窗口正常','可组合申请服务、背景提升、语言/竞赛/科研。',months];return ['规划空间充足','适合长期规划，先做专业探索、竞赛科研、GPA和语言基础。',months]}
function pickProducts(d){let arr=[],c=d.country,s=d.stage,m=d.major,w=d.weaknesses.join(' '),r=d.ranking;if(s==='本科')arr.push('英联邦学术科直通计划');if(s==='本科'&&(r.includes('G5')||r.includes('牛剑')||w.includes('高端')))arr.push('英国本科Mentor领录计划');if(c==='中国香港')arr.push('中国香港维港计划');if(c==='多地联申'||['英国','中国香港','新加坡','澳大利亚','新西兰'].includes(c))arr.push('紫藤留学英才多地计划A','紫藤留学英才多地计划B');if(c==='美国'&&s==='硕士')arr.push('美国研究生高才计划','美国研究生高领计划');if(s==='博士'||w.includes('科研')||w.includes('文书主线弱'))arr.push('博航计划（研究型硕士）','一对一RP辅导');if(c==='欧陆')arr.push('欧陆公立卓越计划');if(c==='日本')arr.push('日本SGU青空优才计划');if(m.includes('商')||m.includes('会计')||m.includes('金融')||m.includes('管理'))arr.push('四大事务所实习','八大事务所实习','名企导师职业规划');if(w.includes('科研')||w.includes('背景活动空白'))arr.push('创新产业科研项目A','英美名校教授小班课远程科研');if(w.includes('GPA')||w.includes('学术成绩'))arr.push('GPA+绩点提升计划20课时');if(m.includes('艺术')||w.includes('作品集'))arr.push('艺术轻藤计划Lite');return [...new Set(arr)].map(n=>products.find(p=>p.name===n)).filter(Boolean).slice(0,9)}
function countryKey(c){return c==='多地联申'?'英国':(schoolPools[c]?c:'英国')}
function schoolReason(d,tier){let base={high:'作为冲刺层，排名和专业竞争更强，适合保留名校机会，但需要更强GPA、语言、文书和背景支撑。',match:'作为主申请层，通常与当前背景匹配度更高，适合承担主要录取结果。',safe:'作为保底层，用来保障offer稳定性，适合时间紧、语言未达标或家长焦虑时配置。'};let cond=[`${d.stage}申请`,`${d.major}方向`,`${d.country}目标地区`,`${d.score}`,`${d.languageTest}${d.languageScore}`];let improve=[];if(d.weaknesses.includes('语言未达标'))improve.push('补语言总分和小分');if(d.weaknesses.includes('GPA/校内成绩弱'))improve.push('补GPA/课程成绩，并增加匹配和保底比例');if(d.weaknesses.includes('实习经历不足'))improve.push('补实习或职业规划，强化文书主线');if(d.weaknesses.includes('科研经历不足'))improve.push('补科研/RP/论文或项目经历');if(d.weaknesses.includes('文书主线弱'))improve.push('梳理专业动机、经历证据和职业目标');if(!improve.length)improve.push('继续补充专业相关经历，并尽早核查官网要求');return {why:base[tier],cond,watch:['官网entry/admission requirements','China list/认可名单/均分门槛','语言小分/先修课/文书/推荐信/截止日期'],improve}}
function schoolCards(d,tier){return (schoolPools[countryKey(d.country)]?.[tier]||[]).map(([cn,en])=>{let r=schoolReason(d,tier);return `<div class="school-card"><h4>${cn}<br><span>${en}</span></h4><p><b>为什么适合：</b>${r.why}</p><p><b>匹配条件：</b>${r.cond.join('｜')}</p><p><b>需要注意：</b>${r.watch.join('；')}</p><p><b>建议提升：</b>${r.improve.join('；')}</p></div>`}).join('')}
function timeline(d){let [risk,tip,months]=timeRisk(d),items=(months<6?['第1周：确认国家/专业/目标院校，核查官网要求与院校名单','第2周：整理成绩单、CV、语言成绩、推荐人和核心经历','第3-4周：定稿冲稳保清单，启动文书和网申材料','1-2个月内：递交第一批申请，同步补语言/面试/背景短项目','递交后：跟进补件、面试、offer、押金和签证']:['现在-1个月：完成背景评估、地区定位、专业定位和初步冲稳保','1-2个月：核查官网要求、China list、语言小分和截止日期','2-4个月：推进语言/GPA/科研/实习/竞赛等短板提升','申请季前3个月：定稿选校、PS/CV/推荐信和材料清单','申请开放后：分批递交，跟进补件/面试/offer/签证']);return `<div class="timeline">${items.map((x,i)=>`<div><b>${i+1}</b><span>${x}</span></div>`).join('')}</div><p class="warning">时间判断：${risk}｜${tip}</p>`}
function buildSearch(d=data()){let c=val('toolCountry')||d.country,st=val('toolStage')||d.stage,maj=val('toolMajor')||d.major,sch=val('toolSchool')||d.targetSchools||'';let q=[sch,maj,st,'entry requirements international students China list tuition deadline'].filter(Boolean).join(' ');let sites=resources[c]||resources[countryKey(c)]||resources['英国'];let google=`https://www.google.com/search?q=${encodeURIComponent(q)}`,bing=`https://www.bing.com/search?q=${encodeURIComponent(q)}`;$('searchLinks').innerHTML=sites.map(([n,u])=>`<div class="link-card"><a href="${u}" target="_blank">${n}</a><p>用于查询${c}项目、课程、要求或院校信息。</p></div>`).join('')+`<div class="link-card"><a href="${google}" target="_blank">Google搜索</a><p>${q}</p><button onclick="copyText('${q.replace(/'/g,"\\'")}')">复制关键词</button></div><div class="link-card"><a href="${bing}" target="_blank">Bing搜索</a><p>备用搜索入口</p></div>`}
function generate(){let d=data(),[risk,tip]=timeRisk(d),ps=pickProducts(d),comp=competitions.filter(x=>d.major.includes(x[0])||x[0].includes(d.major)||d.major==='不确定');if(!comp.length)comp=competitions.slice(0,3);let parent=`家长，我看下来${d.name}现在需要先把“冲刺、匹配、保底”三层定清楚。当前比较匹配的是${d.country}/${d.major}方向，优势是${d.backgrounds.join('、')||'基础信息可继续补充'}，风险在${d.weaknesses.join('、')||'目标和材料还需要进一步确认'}。我建议用${ps[1]?.name||ps[0]?.name||'合适的申请服务'}做主线，同时搭配${ps[3]?.name||'背景提升/语言学术服务'}补竞争力。`;let internal=`画像：${d.identity}/${d.stage}/${d.country}/${d.major}，成绩${d.score}，语言${d.languageTest}${d.languageScore}。主推：${ps.slice(0,3).map(p=>p.name).join('、')}。定校重点：核查官网要求、China list、均分门槛、语言小分、先修课和截止日期。`;let questions=['目前目标地区有没有明确不考虑的？','目标专业是否接受相近专业或跨专业？','成绩单/在读证明/语言成绩是否方便补充？','是否已经咨询过其他机构，对方给的方案是什么？','家里更看重排名、就业、预算还是offer稳定性？','是否接受多地联申来降低风险？','是否有目标院校名单，需要我先按冲稳保核查吗？','是否有实习/科研/竞赛/作品集等证明材料？'];let productPlan=ps.map(p=>`${p.name}（${p.code}｜${p.price}）：${p.desc}`).join('\n');$('output').className='';$('output').innerHTML=`<div class="section-card"><h3>学生画像与核心诊断</h3><div class="summary-grid"><div class="mini-card"><b>申请画像</b><p>${d.identity}｜${d.stage}｜${d.country}｜${d.major}</p></div><div class="mini-card"><b>时间风险：${risk}</b><p>${tip}</p></div><div class="mini-card"><b>核心短板</b><p>${d.weaknesses.join('、')||'待进一步探需'}</p></div></div></div><div class="section-card"><h3>冲稳保院校匹配（中英双语+原因）</h3><div class="plans"><div class="mini-card"><h4>冲刺</h4>${schoolCards(d,'high')}</div><div class="mini-card"><h4>匹配｜主申请层</h4>${schoolCards(d,'match')}</div><div class="mini-card"><h4>保底</h4>${schoolCards(d,'safe')}</div></div><p class="warning">院校名称为顾问初筛方向，最终必须点击查校链接核查官网项目、名单、均分、语言小分和截止日期。</p></div><div class="section-card"><h3>申请推进时间轴</h3>${timeline(d)}</div><div class="section-card"><h3>三套产品组合</h3><div class="plans"><div class="mini-card"><h4>基础方案</h4>${card(ps[0])}${card(ps[3])}</div><div class="mini-card"><h4>进阶方案｜推荐主推</h4>${card(ps[1]||ps[0])}${card(ps[4]||ps[3])}</div><div class="mini-card"><h4>高配方案</h4>${card(ps[2]||ps[1]||ps[0])}${card(ps[5]||ps[4])}</div></div></div><div class="section-card"><h3>背景提升/竞赛建议</h3>${comp.map(x=>`<span class="tag">${x[1]}</span><p>${x[2]}</p>`).join('')}</div><div class="section-card"><h3>探需问题</h3><ol class="list">${questions.map(q=>`<li>${q}</li>`).join('')}</ol></div><div class="section-card"><h3>家长话术</h3><p id="parentTalk">${parent}</p></div><div class="section-card"><h3>内部顾问分析</h3><p id="internalAnalysis">${internal}</p></div><div class="section-card"><h3>产品组合</h3><pre id="productPlan">${productPlan}</pre></div><div id="questions" style="display:none">${questions.join('\n')}</div>`;buildSearch(d)}
function card(p){return p?`<p><b>${p.name}</b><br><span class="tag">${p.code}</span><span class="tag">${p.price}</span><br>${p.desc}</p>`:''}
function fillFilters(){['filterCategory','filterCountry'].forEach(id=>{let key=id==='filterCategory'?'cat':'country';$(id).innerHTML='<option value="">全部'+(key==='cat'?'类型':'地区')+'</option>'+[...new Set(products.map(p=>p[key]))].map(x=>`<option>${x}</option>`).join('')})}
function renderLibrary(){let q=($('productSearch')?.value||'').toLowerCase(),cat=$('filterCategory')?.value||'',c=$('filterCountry')?.value||'';let list=products.filter(p=>(!cat||p.cat===cat)&&(!c||p.country===c)&&JSON.stringify(p).toLowerCase().includes(q));$('productLibrary').innerHTML=list.map(p=>`<div class="product-card"><h3>${p.name}</h3><p><b>${p.code}</b>｜${p.cat}｜${p.country}</p><p>${p.desc}</p><p>${p.price}</p>${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div>`).join('')}
function copyText(t){navigator.clipboard.writeText(t).then(()=>toast())}document.addEventListener('click',e=>{if(e.target.dataset.copy){let el=$(e.target.dataset.copy);copyText(el?el.innerText:'请先生成方案')}if(e.target.dataset.case){let c=e.target.dataset.case;if(c==='case1'){identity.value='大三';stage.value='硕士';country.value='多地联申';major.value='商科金融';budget.value='3-6万';score.value='GPA/均分82';languageScore.value='雅思6.0';targetSchools.value='香港、英国、澳洲商科'}if(c==='case2'){identity.value='国际高中';stage.value='本科';system.value='A-Level';grade.value='G11';country.value='英国';major.value='经济';ranking.value='G5';budget.value='6-10万';targetSchools.value='UCL, LSE, KCL'}if(c==='case3'){identity.value='本科在读';stage.value='博士';country.value='英国';major.value='工程';budget.value='3-6万';score.value='GPA 3.5';targetSchools.value='英国/香港研究型硕士或博士'}generate()}});['generateBtn','schoolPlanBtn'].forEach(id=>$(id).onclick=generate);$('resetBtn').onclick=()=>location.reload();$('printBtn').onclick=()=>window.print();$('buildSearchBtn').onclick=()=>buildSearch();$('saveRulesBtn').onclick=()=>{localStorage.setItem('customRules',$('customRules').value);toast('已保存到本机')};['productSearch','filterCategory','filterCountry'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id)renderLibrary()}));init();